import type { Metadata } from "next";
import "./globals.css";
import Header from './components/server/Header';
import Navigation from './components/client/Navigation';
import { ScrollArea } from "@/components/ui/scroll-area";
import ServiceWorkerRegister from './components/client/ServiceWorkerRegister';

export const metadata: Metadata = {
    title: "Create Next App",
    manifest: "/public/manifest.json",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body className="flex flex-col h-screen bg-white text-[#4a4a68]">
        <ServiceWorkerRegister />
        <Header />
        <ScrollArea className="flex-grow">
            <main className="flex flex-col items-center justify-center p-4 space-y-4">
                {children}
            </main>
        </ScrollArea>
        <Navigation />
        </body>
        </html>
    );
}
// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";
// import ServiceWorkerRegister from './components/client/ServiceWorkerRegister';
// import NetworkStatus from './components/client/NetworkStatus';
//
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
//
// export const metadata: Metadata = {
//   title: "Create Next App",
//   manifest: "/manifest.json",
//   description: "Generated by create next app",
// };
//
// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {/* Service Worker Registration */}
//         <ServiceWorkerRegister />
//
//         {/* Network Status Indicator */}
//         <NetworkStatus />
//
//         {/* Main Application Content */}
//         {children}
//       </body>
//     </html>
//   );
// }
