import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ServiceWorkerRegister from './components/client/ServiceWorkerRegister';
import NetworkStatus from './components/client/NetworkStatus';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  manifest: "/manifest.json",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Service Worker Registration */}
        <ServiceWorkerRegister />

        {/* Network Status Indicator */}
        <NetworkStatus />

        {/* Main Application Content */}
        {children}
      </body>
    </html>
  );
}
