import type { Metadata } from "next";
import "./globals.css";
import ServiceWorkerRegister from './components/ServiceWorkerRegister';
import { AuthProvider } from './auth/AuthContext'

export const metadata: Metadata = {
    title: "Ayudante Mantenimiento",
    manifest: "/manifest.json",
    description: "Aplicación de ayudante de mantenimiento para KOMATSU",
};


export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="es">
        <body className="flex flex-col min-h-screen bg-gray-50">
        <AuthProvider>
        <ServiceWorkerRegister />
        {children}
        </AuthProvider>
        </body>
        </html>
    );
}

// import type { Metadata } from "next";
// import "./globals.css";
// // import { Header } from './components/server/Header';
// import Navigation from './components/client/Navigation';
// import { ScrollArea } from "@/components/ui/scroll-area";
// import ServiceWorkerRegister from './components/client/ServiceWorkerRegister';
//
// export const metadata: Metadata = {
//     title: "Create Next App",
//     manifest: "/public/manifest.json",
//     description: "Generated by create next app",
// };
//
// export default function RootLayout({
//                                        children,
//                                    }: {
//     children: React.ReactNode;
// }) {
//     return (
//         <html lang="en">
//         <body className="flex flex-col h-screen bg-white text-[#4a4a68]">
//         <ServiceWorkerRegister />
//         {/*<Header />*/}
//         <ScrollArea className="flex-grow">
//             <main className="flex flex-col items-center justify-center p-4 space-y-4">
//                 {children}
//             </main>
//         </ScrollArea>
//         <Navigation />
//         </body>
//         </html>
//     );
// }

